### PR TITLE
Merge latest Homebrew/homebrew-test-bot

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
This is needed for e.g. https://github.com/Homebrew/homebrew-science/pull/4647

### CODE REVIEW

**Comment by bw-yuhogg** [comment]
Does this require any changes to `brew` that have happened since 1.0.7? There's a PR open for 1.0.8 (https://github.com/Linuxbrew/brew/pull/174) but it hasn't been merged yet.

(On that note, @sjackman, how's 1.0.8 coming along? I was hoping to get to 1.0.9 this week, and currently Mac Homebrew is at 1.1.1. Don't mean to pester, just checking.)

**Comment by sjackman** [comment]
@rwhogg There's a single failed `brew tests` with `brew tests --only=uses`. The expected output `bar\nbaz` but the output `baz\nbar` is seen instead. I haven't found the time to troubleshoot. I think we could ignore this one failure on Linuxbrew. It's been intermittently showing up for ages. Check out the Docker `linuxbrew/linuxbrew` build history at https://hub.docker.com/r/linuxbrew/linuxbrew/builds/
Because it's intermittent makes it a bit tricky to troubleshoot.

I'll try to merge PR Linuxbrew/brew#174 today, either with a fix, or ignore the test failure.

**Comment by MikeMcQuaid** [comment]
> Does this require any changes to brew that have happened since 1.0.7? There's a PR open for 1.0.8 (Linuxbrew/brew#174) but it hasn't been merged yet.

It may or may not do, I'm not sure.

> There's a single failed brew tests with brew tests --only=uses. The output bar\nbaz but the output baz\nbar is seen instead. I haven't found the time to troubleshoot. I think we could ignore this one failure on Linuxbrew. It's been intermittently showing up for ages. Check out the Docker linuxbrew/linuxbrew build history at https://hub.docker.com/r/linuxbrew/linuxbrew/builds/
> Because it's intermittent makes it a bit tricky to troubleshoot.

I fixed that yesterday: https://github.com/Homebrew/brew/pull/1580. It would be good to try to fix these things, they are pretty trivial. I know I'm a bit of a stuck record but it's worth trying to try and go for the right fix (e.g. work on getting a test failure fixed) rather than a hack (e.g. just disabling `brew tests`). The latter adds technical debt upon technical debt which is going to make it harder and harder to get these two projects ever merged.

**Comment by bw-yuhogg** [comment]
From https://travis-ci.org/Linuxbrew/homebrew-test-bot/jobs/179117377#L791 (the Mac job)
```
Error: undefined local variable or method `tests_args' for #<Homebrew::Test:0x007fbb0b209bf8>
/usr/local/Homebrew/Library/Taps/linuxbrew/homebrew-test-bot/cmd/brew-test-bot.rb:778:in `homebrew'
/usr/local/Homebrew/Library/Taps/linuxbrew/homebrew-test-bot/cmd/brew-test-bot.rb:926:in `run'
/usr/local/Homebrew/Library/Taps/linuxbrew/homebrew-test-bot/cmd/brew-test-bot.rb:1146:in `test_bot'
/usr/local/Homebrew/Library/Taps/linuxbrew/homebrew-test-bot/cmd/brew-test-bot.rb:1229:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:24:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

`tests_args` is used without being defined. The equivalent line in the upstream branch makes no reference to `tests_args`; my guess is that this was deleted upstream.

@MikeMcQuaid, could you make another commit to remove `*tests_args` please? After that, I'm 👍 on merging since everything else passed.

**Comment by sjackman** [comment]
> It would be good to try to fix these things, they are pretty trivial.

I agree. I've taken a few stabs at this issue and come up empty each time.

> `assert_match(/(bar\nbaz|baz\nbar)/, cmd("uses", "--recursive", "foo"))`

This fix is as much a hack as ignoring the test result altogether. Do you know why the result is non-determinstic? I would expect dependencies returned in topological order. The non-deterministic result makes me quite uneasy.

**Comment by sjackman** [comment]
Is it non-determinstic because the formula are iterated over in file-system order, which is arbitrary and variable? If so, would a simple fix be to iterate over the formulae in alphabetical order?

**Comment by sjackman** [comment]
@MikeMcQuaid I forget to say thanks for the fix. This issue has been plaguing me for months. I'm glad to have it resolved finally.

**Comment by sjackman** [comment]
I've merged Homebrew/1.0.8 into Linuxbrew.

**Comment by sjackman** [comment]
Supersed by #3 to address `undefined local variable or method 'tests_args'` and merged #3.

**Comment by sjackman** [comment]
I've submitted six PRs to Homebrew/homebrew-test-bot to support Linux.

**Comment by MikeMcQuaid** [comment]
> This fix is as much a hack as ignoring the test result altogether. Do you know why the result is non-determinstic? I would expect dependencies returned in topological order. The non-deterministic result makes me quite uneasy.

I don't agree. It doesn't matter why the result is non-deterministic. If this was a command where we e.g. guaranteed ordering it would be problematic but it is not so it is not.

**Comment by sjackman** [comment]
It could affect behaviour in unexpected ways when formula are then installed or removed in the ordered returned by `brew uses --recursive`, as for example by `brew test-bot`. When the return value of a function is arbitrary, deterministic and arbitrary is always preferred over random in my opinion, especially when random is only pseudo-random and depends on state you have no control over, such as the file system, and worse for portability is host specific.

**Comment by sjackman** [comment]
I've opened PR https://github.com/Homebrew/brew/pull/1591 to discuss this issue further.

**Pull request merged**
