### PR TITLE
brew-test-bot: Remove linkage test

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by sjackman** [comment]
Would you like to upstream this change? I found it useful.

**Comment by iMichka** [comment]
So here we were testing the linkage of the formula itself. Linkage of dependants was tested a little bit later in the code. I was wondering if I should upstream it or not. I'll go for it if you think it was useful.
I think I have already seen linkage errors like that at the formula level too.

**Comment by iMichka** [comment]
I thought a little bit more about this: superenv should prevent spurious linkage. So this test is not needed.

**Comment by sjackman** [comment]
I don't think we've seen unintended linkage failures in a while, so I'm okay skipping this. File it away as something to bring back though if you do see one.

**Pull request merged**
