### PR TITLE
Merge branch homebrew/master into linuxbrew/master

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
https://github.com/Linuxbrew/homebrew-core/pull/5648 needs to be merged once this one is merged.

**Comment by iMichka** [comment]
@sjackman you wrote:
```
I think that it makes sense to have these parameters default to these values on Linux. It'll affect interactive usage of brew test-bot as well and make it a bit tedious if we have to type these in each time.
```

I would prefer to keep this like this. I personally do not use that command so often, and I just get it back from my history. So once you used it with the right flags, you do not need to care so much. I would like to keep this repo and upstream as much in sync as possible. Is that OK for you?

**Comment by sjackman** [comment]
Yes. It'd be great to get rid of `Linuxbrew/homebrew-test-bot` if it were completely in sync with `Homebrew/homebrew-test-bot`. I'm on board.

**Comment by sjackman** [comment]
Thanks, Michka!

**Pull request closed without merging**
