### PR TITLE
Merge https://github.com/Homebrew/homebrew-test-bot/pull/170

### PR DESCRIPTION
**Pull request by jonchang**

### CODE REVIEW

**Comment by iMichka** [comment]
What are all the other commits? I think these are already merged.

**Comment by iMichka** [comment]
Weird, how did you merge the previous pull request? With squash and merge? Some of the commits in here look like they are already merged, but they are picked up again in your pull request.

**Comment by jonchang** [comment]
Hmm, I have no idea what's going on, all I did was `git merge homebrew/master` from the command line onto a new branch.

**Comment by maxim-belkin** [comment]
@jonchang, it might indicate that you need to `git fetch --all` and `git pull origin` before `git merge`

**Comment by jonchang** [comment]
Thanks all, this is merged.

**Comment by sjackman** [comment]
Thanks, Jon! I'm working on fixing bot.linuxbrew.sh

**Pull request merged**
