### PR TITLE
test-bot: Run brew linkage --reverse for Linuxbrew

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
@imichka Should `test-bot` run `brew linkage --reverse`?

**Comment by iMichka** [comment]
I am not sure why `--reverse` exists. What I would have expect is a `ldd` call on each .so file from the built formula. But I'm Ok with that output too. Maybe it could be run only if there is an exception, so that we do not clutter the log file with unnecessary output?

**Comment by sjackman** [comment]
> I am not sure why --reverse exists.

We inherit this behaviour from Homebrew. You'd have to ask the original author.

> Maybe it could be run only if there is an exception, so that we do not clutter the log file with unnecessary output?

That was my original plan, but I was unsure how to check whether `test "brew", "linkage", "--test", formula_name` failed.

**Comment by iMichka** [comment]
> That was my original plan, but I was unsure how to check whether test "brew", "linkage", "--test", formula_name failed.

I'm afraid the list can get quite long for some formulae. And logs are sometimes long to read, so this does not really help. I think that now that I know that the option exists, I would use it sometimes. But I do not want to have it in the normal output if nothing is wrong.

**Comment by sjackman** [comment]
Closing without merging.

**Pull request closed without merging**
