### PR TITLE
Revert "Revert "Use ActiveSupport Hash#deep_merge" (#111)"

### PR DESCRIPTION
**Pull request by iMichka**
This reverts commit 3135c0d32a0afaa5773320de03c4a99bf1915c8d.

### CODE REVIEW

**Comment by sjackman** [comment]
Is this PR still needed?

**Comment by iMichka** [comment]
Not having this is fine, because the current code works. But we want to stay aligned with upstream.

**Comment by sjackman** [comment]
Oh, I see. This PR reverts the revert. I had missed that.

**Review by sjackman — APPROVED** [review]

**Comment by iMichka** [comment]
Looks like this broke the bottle upload:
```
{"CIRCLE_PR_NUMBER"=>"9634"} /tmp/brew/bin/brew test-bot --ci-upload --bintray-org=linuxbrew --git-name=LinuxbrewTestBot --git-email=testbot@linuxbrew.sh --keep-old
Homebrew/homebrew-test-bot 
ARGV: --ci-upload --bintray-org=linuxbrew --git-name=LinuxbrewTestBot --git-email=testbot@linuxbrew.sh --keep-old
Error: undefined method `deep_merge' for {}:Hash
Did you mean?  deep_merge_hashes
/tmp/brew/Library/Taps/linuxbrew/homebrew-test-bot/cmd/brew-test-bot.rb:1370:in `block in test_ci_upload'
```

**Comment by maxim-belkin** [comment]
Sounds like a job for a "revert revert revert"...?

**Comment by iMichka** [comment]
That's the quick-fix, yes.

The change comes due to: https://github.com/Homebrew/brew/pull/4912

Looks like `global.rb` requires "active_support/core_ext/hash/deep_merge"`. Maybe this is not loaded on our test bot

**Comment by sjackman** [comment]
I've redeployed bot.linuxbrew.sh

**Comment by iMichka** [comment]
That worked!

**Pull request closed without merging**
